apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-webping-pod-updater
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-webping-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-webping-binding
subjects:
- kind: ServiceAccount
  name: sample-webping-pod-updater
  apiGroup: ""
roleRef:
  kind: Role
  name: sample-webping-role
  apiGroup: rbac.authorization.k8s.io

