# permissions for end users to edit coinbasepingers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coinbasepinger-editor-role
rules:
- apiGroups:
  - batch.dev.org
  resources:
  - coinbasepingers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.dev.org
  resources:
  - coinbasepingers/status
  verbs:
  - get
