# permissions for end users to view coinbasepingers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coinbasepinger-viewer-role
rules:
- apiGroups:
  - batch.dev.org
  resources:
  - coinbasepingers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.dev.org
  resources:
  - coinbasepingers/status
  verbs:
  - get
