
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.dev.org
  resources:
  - coinbasepingers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.dev.org
  resources:
  - coinbasepingers/finalizers
  verbs:
  - update
- apiGroups:
  - batch.dev.org
  resources:
  - coinbasepingers/status
  verbs:
  - get
  - patch
  - update
