apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-pinger-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-pinger-role
subjects:
- kind: ServiceAccount
  name: web-pinger-sa
